### ISSUE TITLE
Rename .env file .env.example

### ISSUE THREAD

**Issue by ericpugh** [lucius-digital/openlucius-project#1]
It seems like the convention is to name the default DotEnv file ".env.example". This way someone could track this project as the upstream repository without showing the custom .env as a change.

Just a suggestion. I'm just getting started, but this looks like an **awesome** project.

**Comment by jorislucius** [comment]
Hi Eric, 

Thanks for your issue and compliment, we found some time after a while and did a huge UI update. Will release it officially this Monday. 

.env is now .env.example.
